### ISSUE TITLE
Should cmake check the swig version?

### ISSUE THREAD

**Issue by rmcgibbo** [pandegroup/openmm#1007]
Does anyone know what the minimum version  of swig is that we support? I just logged onto a cluster with a really old version in /usr/bin (1.3.40), and got some garbage.

```
$ make PythonInstall
[  0%] Built target ApiWrappers
[ 51%] Built target OpenMM
[ 51%] Installing OpenMM Python binary module...
OPENMM_LIB_PATH = /home/rmcgibbo/opt/openmm-6.3-dev/lib
OPENMM_INCLUDE_PATH = /home/rmcgibbo/projects/openmm/./include/home/rmcgibbo/projects/openmm/./include/openmm/home/rmcgibbo/projects/openmm/./include/openmm/internal/home/rmcgibbo/projects/openmm/openmmapi/include/home/rmcgibbo/projects/openmm/openmmapi/include/openmm/home/rmcgibbo/projects/openmm/openmmapi/include/openmm/internal/home/rmcgibbo/projects/openmm/olla/include/home/rmcgibbo/projects/openmm/olla/include/openmm/home/rmcgibbo/projects/openmm/olla/include/openmm/internal/home/rmcgibbo/projects/openmm/serialization/include/home/rmcgibbo/projects/openmm/serialization/include/openmm/home/rmcgibbo/projects/openmm/serialization/include/openmm/internal/home/rmcgibbo/projects/openmm/plugins/amoeba/openmmapi/include/home/rmcgibbo/projects/openmm/plugins/amoeba/openmmapi/include/openmm/home/rmcgibbo/projects/openmm/plugins/amoeba/openmmapi/include/openmm/internal/home/rmcgibbo/projects/openmm/plugins/rpmd/openmmapi/include/home/rmcgibbo/projects/openmm/plugins/rpmd/openmmapi/include/openmm/home/rmcgibbo/projects/openmm/plugins/rpmd/openmmapi/include/openmm/internal/home/rmcgibbo/projects/openmm/plugins/drude/openmmapi/include/home/rmcgibbo/projects/openmm/plugins/drude/openmmapi/include/openmm/home/rmcgibbo/projects/openmm/plugins/drude/openmmapi/include/openmm/internal
                                  author                                           Randall J. Radmer
                            author_email                                         radmer@stanford.edu
                                cmdclass{'build_py': <class 'distutils.command.build_py.build_py_2to3'>}
                              data_files                                                          []
                             description                Python wrapper for OpenMM (a C++ MD package)
                            download_url                               https://simtk.org/home/openmm
                             ext_modules  [<distutils.extension.Extension object at 0x7f2274c4f470>]
                                 license               Python Software Foundation License (BSD-like)
                        long_descriptionOpenMM is a library which provides tools for modern molecular
    modeling simulation. As a library it can be hooked into any code,
    allowing that code to do molecular modeling with minimal extra
    coding (https://simtk.org/home/openmm).  This Python package
    gives access to the OpenMM API.

                                    name                                                      OpenMM
                            package_data{'simtk.openmm': [], 'simtk.openmm.app': ['data/*.xml', 'data/*.pdb'], 'simtk': [], 'simtk.unit': [], 'simtk.openmm.app.internal': []}
                                packages['simtk', 'simtk.unit', 'simtk.openmm', 'simtk.openmm.app', 'simtk.openmm.app.internal', 'simtk.openmm.app.internal.charmm', 'simtk.openmm.app.internal.pdbx', 'simtk.openmm.app.internal.pdbx.reader', 'simtk.openmm.app.internal.pdbx.writer']
                               platforms                            ['Linux', 'Mac OS X', 'Windows']
                                     url                               https://simtk.org/home/openmm
                                 version                                                       6.3.0
running install
running build
running build_py
copying simtk/openmm/version.py -> build/lib.linux-x86_64-3.4/simtk/openmm
Skipping implicit fixer: buffer
Skipping implicit fixer: idioms
Skipping implicit fixer: set_literal
Skipping implicit fixer: ws_comma
running build_ext
building 'simtk.openmm._openmm' extension
clang -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=6 -DMINOR_VERSION=3 -I/home/rmcgibbo/projects/openmm/./include -I/home/rmcgibbo/projects/openmm/./include/openmm -I/home/rmcgibbo/projects/openmm/./include/openmm/internal -I/home/rmcgibbo/projects/openmm/openmmapi/include -I/home/rmcgibbo/projects/openmm/openmmapi/include/openmm -I/home/rmcgibbo/projects/openmm/openmmapi/include/openmm/internal -I/home/rmcgibbo/projects/openmm/olla/include -I/home/rmcgibbo/projects/openmm/olla/include/openmm -I/home/rmcgibbo/projects/openmm/olla/include/openmm/internal -I/home/rmcgibbo/projects/openmm/serialization/include -I/home/rmcgibbo/projects/openmm/serialization/include/openmm -I/home/rmcgibbo/projects/openmm/serialization/include/openmm/internal -I/home/rmcgibbo/projects/openmm/plugins/amoeba/openmmapi/include -I/home/rmcgibbo/projects/openmm/plugins/amoeba/openmmapi/include/openmm -I/home/rmcgibbo/projects/openmm/plugins/amoeba/openmmapi/include/openmm/internal -I/home/rmcgibbo/projects/openmm/plugins/rpmd/openmmapi/include -I/home/rmcgibbo/projects/openmm/plugins/rpmd/openmmapi/include/openmm -I/home/rmcgibbo/projects/openmm/plugins/rpmd/openmmapi/include/openmm/internal -I/home/rmcgibbo/projects/openmm/plugins/drude/openmmapi/include -I/home/rmcgibbo/projects/openmm/plugins/drude/openmmapi/include/openmm -I/home/rmcgibbo/projects/openmm/plugins/drude/openmmapi/include/openmm/internal -I/home/rmcgibbo/miniconda/envs/3.4.2/include/python3.4m -c src/swig_doxygen/OpenMMSwig.cxx -o build/temp.linux-x86_64-3.4/src/swig_doxygen/OpenMMSwig.o
src/swig_doxygen/OpenMMSwig.cxx:2226:11: warning: explicitly assigning a variable of type 'int' to itself [-Wself-assign]
                    res = SWIG_AddCast(res);
                    ~~~ ^              ~~~
src/swig_doxygen/OpenMMSwig.cxx:2229:11: warning: explicitly assigning a variable of type 'int' to itself [-Wself-assign]
                    res = SWIG_AddCast(res);
                    ~~~ ^              ~~~
src/swig_doxygen/OpenMMSwig.cxx:2451:20: error: use of undeclared identifier 'PyCObject_Import'; did you mean 'PyObject_Init'?
    type_pointer = PyCObject_Import((char*)"swig_runtime_data" SWIG_RUNTIME_VERSION,
                   ^~~~~~~~~~~~~~~~
                   PyObject_Init
/home/rmcgibbo/miniconda/envs/3.4.2/include/python3.4m/objimpl.h:125:24: note: 'PyObject_Init' declared here
PyAPI_FUNC(PyObject *) PyObject_Init(PyObject *, PyTypeObject *);
                       ^
src/swig_doxygen/OpenMMSwig.cxx:2451:37: error: cannot initialize a parameter of type 'PyObject *' (aka '_object *') with an rvalue of type 'char *'
    type_pointer = PyCObject_Import((char*)"swig_runtime_data" SWIG_RUNTIME_VERSION,
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/rmcgibbo/miniconda/envs/3.4.2/include/python3.4m/objimpl.h:125:48: note: passing argument to parameter here
PyAPI_FUNC(PyObject *) PyObject_Init(PyObject *, PyTypeObject *);
                                               ^
src/swig_doxygen/OpenMMSwig.cxx:2521:23: error: use of undeclared identifier 'PyCObject_FromVoidPtr'
  PyObject *pointer = PyCObject_FromVoidPtr((void *) swig_module, SWIG_Python_DestroyModule);
                      ^
src/swig_doxygen/OpenMMSwig.cxx:2544:37: error: use of undeclared identifier 'PyCObject_AsVoidPtr'
    descriptor = (swig_type_info *) PyCObject_AsVoidPtr(obj);
                                    ^
src/swig_doxygen/OpenMMSwig.cxx:2549:13: error: use of undeclared identifier 'PyCObject_FromVoidPtr'
      obj = PyCObject_FromVoidPtr(descriptor, NULL);
            ^
src/swig_doxygen/OpenMMSwig.cxx:4886:7: error: no matching function for call to 'PySlice_GetIndices'
      PySlice_GetIndices(slice, self->size(), &i, &j, &step);
      ^~~~~~~~~~~~~~~~~~
/home/rmcgibbo/miniconda/envs/3.4.2/include/python3.4m/sliceobject.h:41:17: note: candidate function not viable: no known conversion from 'PySliceObject *' to
      'PyObject *' (aka '_object *') for 1st argument
PyAPI_FUNC(int) PySlice_GetIndices(PyObject *r, Py_ssize_t length,
                ^
src/swig_doxygen/OpenMMSwig.cxx:4895:7: error: no matching function for call to 'PySlice_GetIndices'
      PySlice_GetIndices(slice, self->size(), &i, &j, &step);
      ^~~~~~~~~~~~~~~~~~
/home/rmcgibbo/miniconda/envs/3.4.2/include/python3.4m/sliceobject.h:41:17: note: candidate function not viable: no known conversion from 'PySliceObject *' to
      'PyObject *' (aka '_object *') for 1st argument
PyAPI_FUNC(int) PySlice_GetIndices(PyObject *r, Py_ssize_t length,
                ^
src/swig_doxygen/OpenMMSwig.cxx:4904:7: error: no matching function for call to 'PySlice_GetIndices'
      PySlice_GetIndices(slice, self->size(), &i, &j, &step);
      ^~~~~~~~~~~~~~~~~~
/home/rmcgibbo/miniconda/envs/3.4.2/include/python3.4m/sliceobject.h:41:17: note: candidate function not viable: no known conversion from 'PySliceObject *' to
      'PyObject *' (aka '_object *') for 1st argument
PyAPI_FUNC(int) PySlice_GetIndices(PyObject *r, Py_ssize_t length,
                ^
src/swig_doxygen/OpenMMSwig.cxx:4971:7: error: no matching function for call to 'PySlice_GetIndices'
      PySlice_GetIndices(slice, self->size(), &i, &j, &step);
      ^~~~~~~~~~~~~~~~~~
/home/rmcgibbo/miniconda/envs/3.4.2/include/python3.4m/sliceobject.h:41:17: note: candidate function not viable: no known conversion from 'PySliceObject *' to
      'PyObject *' (aka '_object *') for 1st argument
PyAPI_FUNC(int) PySlice_GetIndices(PyObject *r, Py_ssize_t length,
                ^
src/swig_doxygen/OpenMMSwig.cxx:4980:7: error: no matching function for call to 'PySlice_GetIndices'
      PySlice_GetIndices(slice, self->size(), &i, &j, &step);
      ^~~~~~~~~~~~~~~~~~
/home/rmcgibbo/miniconda/envs/3.4.2/include/python3.4m/sliceobject.h:41:17: note: candidate function not viable: no known conversion from 'PySliceObject *' to
      'PyObject *' (aka '_object *') for 1st argument
PyAPI_FUNC(int) PySlice_GetIndices(PyObject *r, Py_ssize_t length,
                ^
src/swig_doxygen/OpenMMSwig.cxx:4989:7: error: no matching function for call to 'PySlice_GetIndices'
      PySlice_GetIndices(slice, self->size(), &i, &j, &step);
      ^~~~~~~~~~~~~~~~~~
/home/rmcgibbo/miniconda/envs/3.4.2/include/python3.4m/sliceobject.h:41:17: note: candidate function not viable: no known conversion from 'PySliceObject *' to
      'PyObject *' (aka '_object *') for 1st argument
PyAPI_FUNC(int) PySlice_GetIndices(PyObject *r, Py_ssize_t length,
                ^
src/swig_doxygen/OpenMMSwig.cxx:5048:7: error: no matching function for call to 'PySlice_GetIndices'
      PySlice_GetIndices(slice, self->size(), &i, &j, &step);
      ^~~~~~~~~~~~~~~~~~
/home/rmcgibbo/miniconda/envs/3.4.2/include/python3.4m/sliceobject.h:41:17: note: candidate function not viable: no known conversion from 'PySliceObject *' to
      'PyObject *' (aka '_object *') for 1st argument
PyAPI_FUNC(int) PySlice_GetIndices(PyObject *r, Py_ssize_t length,
                ^
src/swig_doxygen/OpenMMSwig.cxx:5057:7: error: no matching function for call to 'PySlice_GetIndices'
      PySlice_GetIndices(slice, self->size(), &i, &j, &step);
      ^~~~~~~~~~~~~~~~~~
/home/rmcgibbo/miniconda/envs/3.4.2/include/python3.4m/sliceobject.h:41:17: note: candidate function not viable: no known conversion from 'PySliceObject *' to
      'PyObject *' (aka '_object *') for 1st argument
PyAPI_FUNC(int) PySlice_GetIndices(PyObject *r, Py_ssize_t length,
                ^
src/swig_doxygen/OpenMMSwig.cxx:5066:7: error: no matching function for call to 'PySlice_GetIndices'
      PySlice_GetIndices(slice, self->size(), &i, &j, &step);
      ^~~~~~~~~~~~~~~~~~
/home/rmcgibbo/miniconda/envs/3.4.2/include/python3.4m/sliceobject.h:41:17: note: candidate function not viable: no known conversion from 'PySliceObject *' to
      'PyObject *' (aka '_object *') for 1st argument
PyAPI_FUNC(int) PySlice_GetIndices(PyObject *r, Py_ssize_t length,
                ^
src/swig_doxygen/OpenMMSwig.cxx:5125:7: error: no matching function for call to 'PySlice_GetIndices'
      PySlice_GetIndices(slice, self->size(), &i, &j, &step);
      ^~~~~~~~~~~~~~~~~~
/home/rmcgibbo/miniconda/envs/3.4.2/include/python3.4m/sliceobject.h:41:17: note: candidate function not viable: no known conversion from 'PySliceObject *' to
      'PyObject *' (aka '_object *') for 1st argument
PyAPI_FUNC(int) PySlice_GetIndices(PyObject *r, Py_ssize_t length,
                ^
src/swig_doxygen/OpenMMSwig.cxx:5134:7: error: no matching function for call to 'PySlice_GetIndices'
      PySlice_GetIndices(slice, self->size(), &i, &j, &step);
      ^~~~~~~~~~~~~~~~~~
/home/rmcgibbo/miniconda/envs/3.4.2/include/python3.4m/sliceobject.h:41:17: note: candidate function not viable: no known conversion from 'PySliceObject *' to
      'PyObject *' (aka '_object *') for 1st argument
PyAPI_FUNC(int) PySlice_GetIndices(PyObject *r, Py_ssize_t length,
                ^
src/swig_doxygen/OpenMMSwig.cxx:5143:7: error: no matching function for call to 'PySlice_GetIndices'
      PySlice_GetIndices(slice, self->size(), &i, &j, &step);
      ^~~~~~~~~~~~~~~~~~
/home/rmcgibbo/miniconda/envs/3.4.2/include/python3.4m/sliceobject.h:41:17: note: candidate function not viable: no known conversion from 'PySliceObject *' to
      'PyObject *' (aka '_object *') for 1st argument
PyAPI_FUNC(int) PySlice_GetIndices(PyObject *r, Py_ssize_t length,
                ^
src/swig_doxygen/OpenMMSwig.cxx:5202:7: error: no matching function for call to 'PySlice_GetIndices'
      PySlice_GetIndices(slice, self->size(), &i, &j, &step);
      ^~~~~~~~~~~~~~~~~~
/home/rmcgibbo/miniconda/envs/3.4.2/include/python3.4m/sliceobject.h:41:17: note: candidate function not viable: no known conversion from 'PySliceObject *' to
      'PyObject *' (aka '_object *') for 1st argument
PyAPI_FUNC(int) PySlice_GetIndices(PyObject *r, Py_ssize_t length,
                ^
src/swig_doxygen/OpenMMSwig.cxx:5211:7: error: no matching function for call to 'PySlice_GetIndices'
      PySlice_GetIndices(slice, self->size(), &i, &j, &step);
      ^~~~~~~~~~~~~~~~~~
/home/rmcgibbo/miniconda/envs/3.4.2/include/python3.4m/sliceobject.h:41:17: note: candidate function not viable: no known conversion from 'PySliceObject *' to
      'PyObject *' (aka '_object *') for 1st argument
PyAPI_FUNC(int) PySlice_GetIndices(PyObject *r, Py_ssize_t length,
                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
2 warnings and 20 errors generated.
error: command 'clang' failed with exit status 1
[100%] Built target PythonInstall
rmcgibbo@sherlock-ln01  ~/projects/openmm/build2 (3.4.2) ‹icc*›

$ swig -version

SWIG Version 1.3.40
```

**Comment by jchodera** [comment]
We should certainly document that somewhere, including the [user guide Installation section](http://docs.openmm.org/6.2.0/userguide/application.html#installing-openmm).

**Comment by rmcgibbo** [comment]
Yeah, but I don't really know what versions work, and I don't really feel like binary-searching...

**Comment by swails** [comment]
1.3.40 works in my hands with gcc/g++.  Where did you get this Python from?  Why is it trying to build extensions with clang?

**Comment by rmcgibbo** [comment]
Python was 3.4. I used clang myself (export CC=clang), but the same error with gcc.

**Comment by rmcgibbo** [comment]
Were you using py3?

**Comment by swails** [comment]
No, Py27 from Miniconda (also works with the system Python 2.6).

**Comment by rmcgibbo** [comment]
Some of the missing C API functions like `PyCObject_FromVoidPtr` are only in the py2 C API, so that's probably it.

**Comment by swails** [comment]
> Some of the missing C API functions like PyCObject_FromVoidPtr are only in the py2 C API, so that's probably it.

That would be my guess.  Based on http://www.swig.org/Release/CHANGES, the absolute *earliest* that Python 3.0 support could have been added is SWIG 1.3.37 (early 2009 release).  1.3.40 was released only 8 months later, and given Python 3's ca. 2009 popularity, I suspect 1.3.40 represented SWIG-Py3 support in its infancy.
