### ISSUE TITLE
Compilation error after refactoring tests

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1154]
The Jenkins `openmm-dev` build is failing with compilation errors (presumably introduced by #1142)
```
[ 38%] Building CXX object platforms/cuda/tests/CMakeFiles/TestCudaAndersenThermostat.dir/TestCudaAndersenThermostat.cpp.o
/home/vagrant/miniconda/conda-bld/work/platforms/cuda/tests/TestCudaAndersenThermostat.cpp:33:10: fatal error: 'TestAndersenThermostat.h' file not found
#include "TestAndersenThermostat.h"
         ^
1 error generated.
make[2]: *** [platforms/cuda/tests/CMakeFiles/TestCudaAndersenThermostat.dir/TestCudaAndersenThermostat.cpp.o] Error 1
make[1]: *** [platforms/cuda/tests/CMakeFiles/TestCudaAndersenThermostat.dir/all] Error 2
make: *** [all] Error 2
```
See [full build logs](https://jenkins.choderalab.org/job/conda-openmm-dev-linux-vagrant-2/125/console).

**Comment by peastman** [comment]
Very strange.  It compiles fine on Travis.  That file should be inside the top level "tests" directory.  And the top level CMakeLists.txt adds that directory to the include path: https://github.com/pandegroup/openmm/blob/master/CMakeLists.txt#L343

**Comment by jchodera** [comment]
Travis doesn't compile the Cuda tests, so it would not have caught this.

Did you potentially just forget to check in a file?  If you did, it would work fine on your machine and travis, but not Jenkins.

**Comment by kyleabeauchamp** [comment]
I can confirm this, I cannot build the latest master:

```
~/src/openmm/platforms/cuda/tests/TestCudaCMAPTorsionForce.cpp:33:34: fatal error: TestCMAPTorsionForce.h: No such file or directory
 #include "TestCMAPTorsionForce.h"
                                  ^
compilation terminated.
~/src/openmm/openmm/platforms/cuda/tests/TestCudaAndersenThermostat.cpp:33:36: fatal error: TestAndersenThermostat.h: No such file or directory
 #include "TestAndersenThermostat.h"
                                    ^
compilation terminated.
~/src/openmm/openmm/platforms/cuda/tests/TestCudaCMMotionRemover.cpp:33:33: fatal error: TestCMMotionRemover.h: No such file or directory
 #include "TestCMMotionRemover.h"
                                 ^
compilation terminated.
~/src/openmm/openmm/platforms/cuda/tests/TestCudaBrownianIntegrator.cpp:33:36: fatal error: TestBrownianIntegrator.h: No such file or directory
 #include "TestBrownianIntegrator.h"
```

**Comment by swails** [comment]
Weird... I can.  I suspect that's probably because I didn't purge my build directory.

I actually tested this because I saw the error @jchodera posted and wondered if I could reproduce it, and I couldn't.  Admittedly I didn't try very hard (I hate compiling everything from scratch and having to reset all of my CMake options).

**Comment by kyleabeauchamp** [comment]
I purged everything.

**Comment by swails** [comment]
Still weird though, since Travis builds fine.  Is your build directory a subdirectory of OpenMM or not?  Because while I didn't purge everything, I still ran `make clean` and re-ran `ccmake`.

**Comment by swails** [comment]
Although Travis doesn't build the CUDA tests...

**Comment by kyleabeauchamp** [comment]
Should those header files be in the source tree?  Because they're not...

**Comment by peastman** [comment]
Sure they are.  They're right here: https://github.com/pandegroup/openmm/tree/master/tests.  And the top level CMakeLists.txt adds that directory to the include path: https://github.com/pandegroup/openmm/blob/master/CMakeLists.txt#L343.

There's nothing CUDA specific there.  All four platforms include exactly the same files.  That's the point, after all.

I wonder if it could somehow be related to the compiler?  I'm using clang.  What about you?

**Comment by swails** [comment]
> I wonder if it could somehow be related to the compiler? I'm using clang. What about you?

clang here

**Comment by swails** [comment]
This doesn't seem like a compiler-specific error, though.  It would seem to be more dependent on how you built everything.  My current guess is that if your build directory is a subdirectory of the OpenMM git repository, it works (as it does for me using clang, and my gcc test using a completely purged build directory just finished successfully, too); but if it's not, it doesn't.

I'm going to check that next.

**Comment by kyleabeauchamp** [comment]
I'm on GCC + Ubuntu 15.04.  I use three directories for building: openmm = github source tree, omm-build is the cmake build tree, and build is the output of make install.

**Comment by swails** [comment]
I did out of source building in a separate directory just now.  Still worked...  My OS is Gentoo, though.

**Comment by jchodera** [comment]
It fails on `osx` too:
```
Linking CXX shared library ../../../libOpenMMOpenCL.dylib
/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/conda-bld/work/platforms/cuda/tests/TestCudaCMMotionRemover.cpp:33:10: fatal error: 'TestCMMotionRemover.h' file not found
#include "TestCMMotionRemover.h"
         ^
1 error generated.
make[2]: *** [platforms/cuda/tests/CMakeFiles/TestCudaCMMotionRemover.dir/TestCudaCMMotionRemover.cpp.o] Error 1
make[1]: *** [platforms/cuda/tests/CMakeFiles/TestCudaCMMotionRemover.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/conda-bld/work/platforms/cuda/tests/TestCudaCustomBondForce.cpp:33:10: fatal error: 'TestCustomBondForce.h' file not found
#include "TestCustomBondForce.h"
         ^
/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/conda-bld/work/platforms/cuda/tests/TestCudaCustomAngleForce.cpp:33:10: fatal error: 'TestCustomAngleForce.h' file not found
#include "TestCustomAngleForce.h"
         ^
1 error generated.
make[2]: *** [platforms/cuda/tests/CMakeFiles/TestCudaCustomBondForce.dir/TestCudaCustomBondForce.cpp.o] Error 1
make[1]: *** [platforms/cuda/tests/CMakeFiles/TestCudaCustomBondForce.dir/all] Error 2
/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/conda-bld/work/platforms/cuda/tests/TestCudaCheckpoints.cpp:33:10: fatal error: 'TestCheckpoints.h' file not found
#include "TestCheckpoints.h"
         ^
/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/conda-bld/work/platforms/cuda/tests/TestCudaAndersenThermostat.cpp:33:10: fatal error: 'TestAndersenThermostat.h' file not found
#include "TestAndersenThermostat.h"
         ^
1 error generated.
/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/conda-bld/work/platforms/cuda/tests/TestCudaCMAPTorsionForce.cpp:33:10: fatal error: 'TestCMAPTorsionForce.h' file not found
#include "TestCMAPTorsionForce.h"
         ^
/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/conda-bld/work/platforms/cuda/tests/TestCudaBrownianIntegrator.cpp:33:10: fatal error: 'TestBrownianIntegrator.h' file not found
#include "TestBrownianIntegrator.h"
         ^
make[2]: *** [platforms/cuda/tests/CMakeFiles/TestCudaCustomAngleForce.dir/TestCudaCustomAngleForce.cpp.o] Error 1
make[1]: *** [platforms/cuda/tests/CMakeFiles/TestCudaCustomAngleForce.dir/all] Error 2
[ 86%] 1 error generated.
Built target OpenMMOpenCL
1 error generated.
1 error generated.
1 error generated.
make[2]: *** [platforms/cuda/tests/CMakeFiles/TestCudaAndersenThermostat.dir/TestCudaAndersenThermostat.cpp.o] Error 1
make[1]: *** [platforms/cuda/tests/CMakeFiles/TestCudaAndersenThermostat.dir/all] Error 2
make[2]: *** [platforms/cuda/tests/CMakeFiles/TestCudaCheckpoints.dir/TestCudaCheckpoints.cpp.o] Error 1
make[1]: *** [platforms/cuda/tests/CMakeFiles/TestCudaCheckpoints.dir/all] Error 2
make[2]: *** [platforms/cuda/tests/CMakeFiles/TestCudaCMAPTorsionForce.dir/TestCudaCMAPTorsionForce.cpp.o] Error 1
make[2]: *** [platforms/cuda/tests/CMakeFiles/TestCudaBrownianIntegrator.dir/TestCudaBrownianIntegrator.cpp.o] Error 1
make[1]: *** [platforms/cuda/tests/CMakeFiles/TestCudaCMAPTorsionForce.dir/all] Error 2
make[1]: *** [platforms/cuda/tests/CMakeFiles/TestCudaBrownianIntegrator.dir/all] Error 2
make: *** [all] Error 2
```
Full build logs available [here](https://jenkins.choderalab.org/job/conda-openmm-dev-osx-2/130/console).

**Comment by jchodera** [comment]
As a reminder, the recipe that is used to compile these `openmm-dev` packages on Jenkins is here:
https://github.com/omnia-md/openmm-dev/blob/master/openmm-dev/build.sh

The recipe uses `clang`.

The build system hasn't been updated in a while, so we are still using the same `clang` version as before.

On the `linux` VM, this is 
```
[vagrant@localhost ~]$ clang --version
clang version 3.4.2 (tags/RELEASE_34/dot2-final)
Target: x86_64-redhat-linux-gnu
Thread model: posix
```
on `osx`, this is
```
mski1620:conda-openmm-dev-linux-vagrant-2 jenkins-slave$ clang --version
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
```

The builds are always clean builds inside of a newly-installed `miniconda` environment.

Again, travis doesn't test CUDA, though I wish we could find some way to do that.  (We can surely *install* the CUDA SDK and build the CUDA libraries and tests on travis, can't we?  Even if we can't run the tests?)

**Comment by peastman** [comment]
> Again, travis doesn't test CUDA

Is CUDA the only platform that fails, or does it just happen to be the first one it gets to?  Try disabling building the CUDA platform.  Does everything else work, or does it then fail on a different platform?

**Comment by jchodera** [comment]
Do you have `vagrant` and virtualbox installed, @peastman?  I can just give you info on how to spin up an identical copy of the VM to debug in.

**Comment by jchodera** [comment]
Here you go, @peastman:
```
git clone https://github.com/omnia-md/virtual-machines
cd virtual-machines/linux
vagrant up
vagrant ssh
```
You'll need [vagrant](https://www.vagrantup.com/) and [virtualbox](https://www.virtualbox.org/wiki/Downloads) with the latest [guest additions](http://download.virtualbox.org/virtualbox/5.0.4/Oracle_VM_VirtualBox_Extension_Pack-5.0.4-102546.vbox-extpack) installed.

Provisioning may take an hour or so, but then you will have access to the exact build environment.

**Comment by peastman** [comment]
> Do you have vagrant and virtualbox installed

No, I don't.  Could you try the test I suggested?  You should be able to debug this pretty quickly.  Either you're somehow missing the files, or the directory somehow isn't getting added to your include path.

**Comment by jchodera** [comment]
Er, it's not *my* path.  It's the path in the `openmm-dev` recipe:
https://github.com/omnia-md/openmm-dev

Because of the automation, debugging would involve making a bunch of commits to that repo and retriggering the build numerous times, and even then, I'd have to instrument the build script to even inspect what is going on with directories.  It's not interactive debugging in a shell.

If disabling the CUDA platform and reporting success or failure is literally the only thing you want me to try, I can do that in about five minutes and would be happy to try that.  If there are any more steps in the debugging process, it's going to be a lot harder.

**Comment by peastman** [comment]
@kyleabeauchamp you said you could also reproduce the problem.  Are you able to do it in a setting more amenable to debugging?  Turning off the CUDA platform is the first step in debugging, but not necessarily the last.

**Comment by kyleabeauchamp** [comment]
Will take a look tonight

**Comment by kyleabeauchamp** [comment]
OK, so the compilation error only appears when I *disable* build_testing in ccmake.  If I re-enable it, we're OK.  Try that.

**Comment by swails** [comment]
Isn't that really weird?  Shouldn't disabling build_testing prevent those files from even *trying* to be built?

**Comment by kyleabeauchamp** [comment]
Yeah, it's weird.  My procedure was

1.  git clone
2.  mkdir omm-build
3.  cd omm-build
4.  ccmake ../openmm
5.  Change build_testing and root dir, generate
6.  make install

**Comment by kyleabeauchamp** [comment]
FWIW, I can also reproduce this on the cbio cluster.  That might be the easiest way to reproduce.

**Comment by peastman** [comment]
>  Shouldn't disabling build_testing prevent those files from even trying to be built?

Yes!  Ok, that's a great lead.  I'm out of the office today, but I'll follow up on it tomorrow.  Thanks!
