### ISSUE TITLE
Create 7.1.1 patch release

### ISSUE THREAD

**Issue by peastman** [pandegroup/openmm#1793]
There've been a few bugs found in 7.1 that probably justify doing a patch release.  These are the changes I think are worth considering for inclusion:

#1731 (Fix substeps division in MTSIntegrator)
#1752 (Fixed error adding triclinic solvent boxes)
#1756 (Fixed bugs in multipoles with ZOnly axis type)
#1761 (Fix bug where CHARMM impropers did not respect toroidal boundary conditions)
#1767 (Fixed error with exclusions for Drude particles)
#1784 (Fixed bug accessing parameters for CustomHbondForce)
#1792 (Bug fixes to CustomHbondForce)

Any thoughts on them?

**Comment by jchodera** [comment]
All of these look good!

Relatedly, have we been diligent about tagging bugs with the `bug` label, or is it possible some have slipped by so we can't just sort closed issues by label to find the critical ones?

**Comment by Lnaden** [comment]
Might I also suggest #1757 (Allow docs to build in Sphinx 1.3.1 and 1.5.1) so we don't have to [re-make the patch](https://github.com/omnia-md/conda-recipes/blob/master/openmm/durole.patch) to get the docs to build in order to support Python 3.6?

**Comment by peastman** [comment]
Sounds reasonable.

**Comment by peastman** [comment]
I think we're ready to build a release candidate.  It should be built from the head of `7.1_branch`.  As we discussed in #1733, it will be called simply `7.1.1`.  If we need to do another release candidate, the version number will remain the same but we'll update the build number.

**Comment by peastman** [comment]
And because of course nothing related to building on Windows can ever be straightforward, it's failing with a link error related to FFTW:

```
libfftw3f-3.lib(timer.obj) : error LNK2019: unresolved external symbol __imp_clock referenced in function fftwf_elapsed_since
..\..\OpenMMPME.dll : fatal error LNK1120: 1 unresolved externals
LINK failed. with 1120
```

I don't know why it's failing now when the same build script worked a few months ago.  This is building the zip installer, compiling against the conda FFTW build.  Is it possible that has gotten rebuilt since 7.1 was released?

**Comment by Lnaden** [comment]
I don't think so. Last upload of the `fftw3f` on omnia was [over a year ago](https://anaconda.org/omnia/fftw3f/files), its old enough now that some new conda builds are complaining because it was built on an old `conda-build`

**Comment by peastman** [comment]
Since we haven't managed to get this built yet, I'd like to add one more fix: #1806.

**Comment by Lnaden** [comment]
Seems reasonable

**Comment by peastman** [comment]
The Windows conda builds are failing.  It looks like it's trying to build fftw rather than just using the prebuilt one:

```
(C:\Miniconda3\conda-bld\fftw3f_1494375748322\_b_env) C:\Miniconda3\conda-bld\fftw3f_1494375748322\work\fftw-3.3.4>IF "64" == "32" (
copy C:\Users\rmcgibbo\projects\fftw-3.3.4\fftw-3.3-libs\Static-Release\libfftw-3.3.lib C:\Miniconda3\conda-bld\fftw3f_1494375748322\_b_env\Library\lib\
 copy C:\Users\rmcgibbo\projects\fftw-3.3.4\fftw-3.3-libs\Static-Release\libfftwf-3.3.lib C:\Miniconda3\conda-bld\fftw3f_1494375748322\_b_env\Library\lib\
)  ELSE (
copy C:\Users\rmcgibbo\projects\fftw-3.3.4\fftw-3.3-libs\x64\Static-Release\libfftw-3.3.lib C:\Miniconda3\conda-bld\fftw3f_1494375748322\_b_env\Library\lib\
 copy C:\Users\rmcgibbo\projects\fftw-3.3.4\fftw-3.3-libs\x64\Static-Release\libfftwf-3.3.lib C:\Miniconda3\conda-bld\fftw3f_1494375748322\_b_env\Library\lib\
)
The system cannot find the path specified.
The system cannot find the path specified.

(C:\Miniconda3\conda-bld\fftw3f_1494375748322\_b_env) C:\Miniconda3\conda-bld\fftw3f_1494375748322\work\fftw-3.3.4>copy C:\Users\rmcgibbo\projects\fftw-3.3.4\api\fftw3.h C:\Miniconda3\conda-bld\fftw3f_1494375748322\_b_env\Library\include\
The system cannot find the path specified.
```

I already have it installed:

```
c:\Users\vagrant\conda-recipes>"C:\Miniconda3\Scripts\conda.exe" list
# packages in environment at C:\Miniconda3:
#
...
fftw3f                    3.3.4                    vc14_2  [vc14]  omnia
```

Here's the command line I'm using to build:

```
"C:\Miniconda3\Scripts\conda.exe" build -c omnia --python 3.6 openmm
```

Any idea what's going on?

**Comment by jchodera** [comment]
Is it possible it's related to this issue in the latest `conda-build` 2.1.12?

https://github.com/conda/conda-build/issues/2008

**Comment by msarahan** [comment]
@jchodera that does not look related to that issue.  Does your destination directory exist at the time you try to copy the file?  I think the folders you show there are created by default, but I'm not completely certain.  It is always wise to verify that a folder exists before trying to copy something into it.

Also, I'm not sure why you're copying files from a folder outside of what conda-build controls.  If it's not part of your source section in meta.yaml, you really shouldn't depend on it being there.

**Comment by peastman** [comment]
I'm not copying anything.  All of that is just conda trying to satisfy dependencies before it even begins building OpenMM.  It appears that it's trying to build FFTW by using the recipe at https://github.com/omnia-md/conda-recipes/tree/master/fftw3f, instead of by installing the already built package from the omnia channel.

**Comment by msarahan** [comment]
Please link me to a build log.  It's definitely not that bug, but it could well be another bug.

From the package list at https://anaconda.org/omnia/fftw3f/files it is odd that you only have a vc14 package.  I would expect that you need vc9, vc10, and vc14 packages for python 2.7, 3.4, 3.5+, respectively.  That might be why conda-build is trying to build fftw3f, rather than use the package that you already have.  Conda-build will definitely want vc9 for python 2.7.

**Comment by peastman** [comment]
We only support Python 3.5 and 3.6 on Windows.  That's why we only have a vc14 version of FFTW.

**Comment by peastman** [comment]
Figured it out...  If I cd to the conda-recipes directory and type `conda build ... openmm`, that produces the error.  But if I cd to the parent directory and type `conda build ... conda-recipes/openmm`, that works.  Apparently it looks in your current directory for other directories containing recipes, and uses those automatically.  Conda is a remarkably brittle tool.

Anyway, Windows conda installers are built!  I think the only thing that's left is the zip installers for Mac and Linux?

**Comment by msarahan** [comment]
It should only go looking for other recipes if it fails to install them when creating environments.  Something is going wrong.  I'd be happy to look into it if you can come up with a simple reproducing example.

**Comment by jchodera** [comment]
@msarahan : That would be fantastic---thanks so much for the offer to help us debug this!

@peastman : Could you at least document (or point to the documentation) of precisely what you did to reproduce the issue?

**Comment by peastman** [comment]
Thanks @msarahan.  I'll see if I can put together some simple instructions.

**Comment by peastman** [comment]
Who's building the zip installers?  @jchodera built them for the last release.

**Comment by jchodera** [comment]
I'll do it. Sorry for the delay.

**Comment by jchodera** [comment]
@Lnaden : If we've finished the 7.1.1 conda builds, can we migrate to the CentOS 6 build infrastructure for omnia now?

**Comment by peastman** [comment]
Let's wait till it's actually released.  We may still have to do another build.

**Comment by jchodera** [comment]
@Lnaden : Any idea why I might be running into LaTeX issues with this build on the `omnia-build-box:cuda80-amd30-clang38` docker image?
```
(/usr/local/texlive/2015/texmf-dist/tex/latex/psnfss/times.sty)

! LaTeX Error: File `fncychap.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! LaTeX Error: Missing \begin{document}.
```

**Comment by Lnaden** [comment]
>  If we've finished the 7.1.1 conda builds, can we migrate to the CentOS 6 build infrastructure for omnia now? 

I agree with @peastman for the same reason, hold off on that

> Any idea why I might be running into LaTeX issues with this build on the..

Yes. I never actually fixed the Centos5 pre-conda-forge Docker file. I fixed the missing LaTeX packages in the `docker-build.sh` file here: https://github.com/omnia-md/conda-recipes/blob/9ec975a03c619e59f0f487ce7ed9159588a4c6ae/devtools/docker-build.sh#L16

It was faster and easier to add the missing LaTeX packages as part of that rather then try to get Docker to correctly rebuild and test the Docker image for CentOS 5 at the time. I also did not know enough about how the docker images were built at the time to fix that quickly, so I opted to do it there instead

**Comment by jchodera** [comment]
@peastman:

* https://s3.amazonaws.com/omnia-ci/OpenMM+7.1.1/OpenMM-7.1.1-Linux.tgz
* https://s3.amazonaws.com/omnia-ci/OpenMM+7.1.1/OpenMM-7.1.1-Linux.zip
* https://s3.amazonaws.com/omnia-ci/OpenMM+7.1.1/OpenMM-7.1.1-Mac.tgz
* https://s3.amazonaws.com/omnia-ci/OpenMM+7.1.1/OpenMM-7.1.1-Mac.zip
* https://s3.amazonaws.com/omnia-ci/OpenMM+7.1.1/OpenMM-7.1.1-Source.tgz
* https://s3.amazonaws.com/omnia-ci/OpenMM+7.1.1/OpenMM-7.1.1-Source.zip

**Comment by peastman** [comment]
The Mac zip is missing all the CUDA plugins.

**Comment by jchodera** [comment]
Sorry about that. Installed CUDA 8.0 and rebuilt the Mac ZIP. The plugins should be there now:
```
lski1962:packaging choderaj$ ls -ltr packaging/OpenMM-7.1.1-Mac/lib/plugins/
total 12568
-rwxr-xr-x  1 choderaj  9696963    52484 May 12 20:46 libOpenMMRPMDReference.dylib
-rwxr-xr-x  1 choderaj  9696963   125372 May 12 20:46 libOpenMMRPMDOpenCL.dylib
-rwxr-xr-x  1 choderaj  9696963   118812 May 12 20:46 libOpenMMRPMDCUDA.dylib
-rwxr-xr-x  1 choderaj  9696963    61528 May 12 20:46 libOpenMMPME.dylib
-rwxr-xr-x  1 choderaj  9696963  2132728 May 12 20:46 libOpenMMOpenCL.dylib
-rwxr-xr-x  1 choderaj  9696963    56324 May 12 20:46 libOpenMMDrudeReference.dylib
-rwxr-xr-x  1 choderaj  9696963    93424 May 12 20:46 libOpenMMDrudeOpenCL.dylib
-rwxr-xr-x  1 choderaj  9696963    86964 May 12 20:46 libOpenMMDrudeCUDA.dylib
-rwxr-xr-x  1 choderaj  9696963    54728 May 12 20:46 libOpenMMCudaCompiler.dylib
-rwxr-xr-x  1 choderaj  9696963  1936764 May 12 20:46 libOpenMMCUDA.dylib
-rwxr-xr-x  1 choderaj  9696963   479088 May 12 20:46 libOpenMMCPU.dylib
-rwxr-xr-x  1 choderaj  9696963   471060 May 12 20:46 libOpenMMAmoebaReference.dylib
-rwxr-xr-x  1 choderaj  9696963   738208 May 12 20:46 libOpenMMAmoebaCUDA.dylib
```

**Comment by peastman** [comment]
Thanks!  The zip installers are now up at https://simtk.org/frs/?group_id=161 under the "hidden releases" link.  Now we need to test all the installers (both conda and zip) as described in step 3 at https://github.com/pandegroup/openmm/wiki/Release-Candidates.  The git revision should be c1a64aaa3b4b71f8dd9648fa724d2548a99d4ced.  Anyone who cares to help out by testing any of the installers, that would be really appreciated.  Here's a checklist for keeping track of them.

- [ ] Linux conda
- [ ] Linux zip
- [ ] Mac conda
- [ ] Mac zip
- [ ] WIndows conda
- [ ] Windows zip

**Comment by peastman** [comment]
I had to create new Windows conda installers.  For some reason the original ones were missing the CUDA platform, and I had to modify the recipe to tell it where CUDA was installed.  There's also a problem with the Windows zip installer.  For some reason, the Python API installer is getting built for 32 bit Python.  I have no idea why, given that I'm building it with a 64 bit Python!  I'll try to figure that out.

If anyone else cares to test Linux and/or Mac installers, that would be really appreciated.

**Comment by peastman** [comment]
It looks like that's caused by a bug in the conda version of Python 3.6.  By downloading the standard (non-conda) Python, I was able to build a proper installer.  Fixed version of the Windows zip installer is posted.

**Comment by peastman** [comment]
I've tested the conda and zip installers for Linux on Python 3.5.  They both work.

**Comment by peastman** [comment]
Mac installers are tested too.  I'll go ahead and post on the forum to invite other people to try it.

**Comment by peastman** [comment]
I've gotten no reports of any problems.  Shall I go ahead and release it?

**Comment by jchodera** [comment]
I'd go for it! We're all around and can pull it down if any unexpected problems arise.

**Comment by peastman** [comment]
It's released on both conda and simtk.org, and I've created the github release.  I'll post the announcement on simtk.org next.  I'll go ahead and close this issue.  We can reopen it if any problems come up.
